[memory]
ram = { size = "128K",  origin = 0x20000000 }
flash = { size = "1M", origin = 0x08000000 }

[heap.main]
size = "64K"
pools = [
    { block = "4", capacity = 755 },
    { block = "20", capacity = 377 },
    { block = "108", capacity = 97 },
    { block = "324", capacity = 38 },
    { block = "708", capacity = 17 },
    { block = "1304", capacity = 8 },
    { block = "2148", capacity = 3 },
    { block = "3276", capacity = 1 },
]

[linker]
platform = "arm"
